### ISSUE TITLE
diff.js & patch.js中的问题

### ISSUE THREAD

**Issue by ansenAC** [viclm/jquery-widget#1]
Hi,

项目中发现一个问题，在diff.js中 如果你将一个dom节点标记为REPLACE，则会停止递归调用diff中的this.walk()方法，这样，会忽略已删除节点的孩子的差异

但是在patch.js中，你在patchReplace删除该节点后，仍然会递归遍历其孩子节点，这样造成this.walk中传入的节点与this.patchs中相比较的节点层次不一致。最终diff结果错误

**Comment by viclm** [comment]
Turn to pull request  #2
